#!/bin/bash

# ======================================================================
# ======================================================================
rm -Rf /opt/nginx/modules/
mkdir -p /opt/nginx/modules/
# ======================================================================
cd /opt/nginx/modules/
wget https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.3-stable.zip
unzip v1.12.34.3-stable.zip; rm -Rf v1.12.34.3-stable.zip
# ======================================================================

# ======================================================================
# PAGESPEED LIBRARY.
# ======================================================================
cd /opt/nginx/modules/ngx_pagespeed-1.12.34.3-stable
wget https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz
tar -xzvf 1.12.34.2-x64.tar.gz; rm -Rf 1.12.34.2-x64.tar.gz
# ======================================================================

# ======================================================================
# DWL MODS.
# ======================================================================
cd /opt/nginx/modules/
git clone https://github.com/nbs-system/naxsi.git
git clone https://github.com/kyprizel/testcookie-nginx-module.git
git clone https://github.com/openresty/headers-more-nginx-module.git
git clone https://github.com/openresty/echo-nginx-module.git
git clone https://github.com/arut/nginx-dav-ext-module.git
git clone https://github.com/nginx-clojure/nginx-access-plus.git
git clone https://github.com/leev/ngx_http_geoip2_module.git
git clone https://github.com/dizballanze/ngx_http_avatars_gen_module.git
git clone https://github.com/arut/nginx-mtask-module.git
git clone https://github.com/arut/nginx-mysql-module.git
git clone https://github.com/openresty/encrypted-session-nginx-module.git
git clone https://github.com/simpl/ngx_devel_kit.git
# ======================================================================

# ======================================================================
# SHOULD MATCH NGINX PLUS VERSION.
# ======================================================================
mkdir -p /opt/nginx/sources/; cd /opt/nginx/sources/
wget 'http://nginx.org/download/nginx-1.13.4.tar.gz'
tar -xzvf nginx-1.13.4.tar.gz; rm -Rf nginx-1.13.4.tar.gz
# ======================================================================

# ======================================================================
# BUILD.
# ======================================================================
cat <<EOF > /opt/nginx/sources/nginx-1.13.4/build.sh
./configure \
--with-compat \
--add-dynamic-module=/opt/nginx/modules/ngx_devel_kit \
--add-dynamic-module=/opt/nginx/modules/naxsi/naxsi_src \
--add-dynamic-module=/opt/nginx/modules/testcookie-nginx-module \
--add-dynamic-module=/opt/nginx/modules/headers-more-nginx-module \
--add-dynamic-module=/opt/nginx/modules/echo-nginx-module \
--add-dynamic-module=/opt/nginx/modules/nginx-dav-ext-module \
--add-dynamic-module=/opt/nginx/modules/nginx-access-plus/src/c \
--add-dynamic-module=/opt/nginx/modules/ngx_http_geoip2_module \
--add-dynamic-module=/opt/nginx/modules/ngx_http_avatars_gen_module \
--add-dynamic-module=/opt/nginx/modules/nginx-mtask-module \
--add-dynamic-module=/opt/nginx/modules/nginx-mysql-module \
--add-dynamic-module=/opt/nginx/modules/ngx_pagespeed-1.12.34.3-stable \
--add-dynamic-module=/opt/nginx/modules/encrypted-session-nginx-module
EOF
# ======================================================================
cd /opt/nginx/sources/nginx-1.13.4/; chmod +x build.sh
./build.sh
make modules
rm -Rf /etc/nginx/modules/
cp -a /opt/nginx/sources/nginx-1.13.4/objs/ /etc/nginx/modules/
clear
# ======================================================================
