#!/bin/bash

download() {
cd /
wget https://github.com/systemroot/my-nginx/raw/master/nginx-plus/nginx-plus.zip
unzip -P ****** nginx-plus.zip; rm -Rf nginx-plus.zip
clear
}

rebuild-conf() {

}

download-mods() {

}

compile-mods() {

}

move-mods() {

}
