#!/bin/bash
#After.
useradd -r nginx
rm -Rf /etc/init.d/nginx
cd /etc/init.d/
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/etc/init.d/nginx
chmod +x nginx
mkdir -p /etc/nginx/
cd /etc/nginx/
mkdir conf.d
rm -Rf nginx.conf*
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/stream/nginx.conf
mkdir -p /nginx/sites/
cd /nginx/sites/
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/nginx/sites/default
mkdir -p /hostdata/default
cd /hostdata/default
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/stream/index.html

clear
echo "If You execute 'service nginx start' you should see nginx default page."
