#!/bin/bash
useradd www-data
cd /
apt-get install git -y
git clone who
unzip who
rm -Rf who
#
mkdir -p var/cache/nginx
mkdir -p /var/log/nginx
touch /var/log/nginx/access.log
touch /var/log/nginx/error.log
#
service nginx start

