#!/bin/bash

useradd -r nginx
rm -Rf /etc/init.d/nginx
cd /etc/init.d/
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/nginx-as-firewall/static/nginx
chmod +x nginx
cd /nginx/
mkdir conf.d
rm -Rf nginx.conf*
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/nginx-as-firewall/static/nginx.conf
mkdir -p /nginx/live/
cd /nginx/live/
wget https://raw.githubusercontent.com/systemroot/my-nginx/master/nginx-as-firewall/static/default

mkdir -p /hostdata/default
mkdir -p /hostdata/default/public_html
mkdir -p /hostdata/default/logs
mkdir -p /hostdata/default/cache
cd /hostdata/default/public_html/

wget https://raw.githubusercontent.com/systemroot/my-nginx/master/hostdata/default/index.html

clear
echo "||================================================||"
echo "||================================================||"
echo "||============= Nginx |=> FIXED 100% =============||"
echo "||------------------------------------------------||"
echo "||============= PATH  |=> /nginx/ ================||"
echo "||------------------------------------------------||"
echo "||============= CONF  |=> /nginx/nginx.conf ======||"
echo "||------------------------------------------------||"
echo "||============= VHOST |=> /nginx/live/ ===========||"
echo "||================================================||"
echo "||================================================||"
echo "||------------------------------------------------||"
echo "||================================================||"
echo "||================================================||"
echo "||============= CHECK |=> nginx -t ===============||"
echo "||------------------------------------------------||"
echo "||============= START |=> service nginx start ====||"
echo "||------------------------------------------------||"
echo "||============= STOP  |=> service nginx stop =====||"
echo "||------------------------------------------------||"
echo "||=========== RESTART |=> service nginx restart ==||"
echo "||------------------------------------------------||"
echo "||================================================||"
echo "||================================================||"
echo "||=========== Install php5.6-fpm => ./setup iphp =||"
