#!/bin/bash
# Nginx 1.9.9 + * Modules.
# Author RAW. // systemroot.me
##########################
# ==============================================
# Check..
# ==============================================
if [ "$(whoami)" != "root" ]
then
    echo "You should Login as root to use this script!";
    echo "May you already have access for sudo, but commands aren't designed with sudo! so..";
    echo "sudo -i";
    exit 1
fi

if [ -d "/nginx/sites" ]; then
    echo "We've detect a folder '/nginx/sites' which means"
    echo "Maybe you have use this script before!"
    echo "All what you can do now is to remove '/nginx/' dir manually!"
    exit 1
fi

if [ -d "/etc/nginx" ]; then
    echo "We've detect a folder '/etc/nginx' which means"
    echo "Maybe you have use this script before!"
    echo "All what you can do now is to remove '/etc/nginx/' dir manually!"
    exit 1
fi

if [ -d "/opt/nginx/" ]; then
    echo "We've detect a folder '/opt/nginx/' which means"
    echo "Maybe you have use this script before!"
    echo "All what you can do now is to remove '/opt/nginx/' dir manually!"
    echo "And if you've install nginx please use =>"
    echo "apt-get update; apt-get upgrade; apt-get dist-upgrade"
    echo "apt-get purge nginx; apt-get autoremove"
    exit 1
fi
# ==============================================
# ==============================================
#Before.
apt-get update -y
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get install apt-utils build-essential -y
apt-get install git -y
apt-get install checkinstall libpcre3 libpcre3-dev zlib1g zlib1g-dbg libxml2 zlib1g-dev -y
apt-get install -y unzip
apt-get install -y libicu-dev libcurl4-gnutls-dev libtool
apt-get install -y libmozjs-24-dev
apt-get install -y libmozjs-24-bin; sudo ln -sf /usr/bin/js24 /usr/bin/js
apt-get install openssl libssl-dev libperl-dev libexpat-dev -y
apt-get install mercurial meld -y
apt-get install libxslt-dev -y
apt-get install libgd2-xpm -y
apt-get install libgd2-xpm-dev -y
apt-get install libgeoip-dev -y
apt-get install libssl libssl-dev -y
apt-get install dh-autoreconf -y
apt-get install -y software-properties-common
apt-get install -y python-software-properties
apt-get install -y libcairo2 libcairo2-dev
apt-get install -y python-dev
apt-get install libmysqlclient-dev -y
apt-get install libmariadbclient-dev -y
sudo add-apt-repository ppa:maxmind/ppa -y
apt-get install aptitude -y
aptitude update -y
aptitude upgrade -y
aptitude install libmaxminddb0 libmaxminddb-dev mmdb-bin -y

#Dirs!
mkdir -p /nginx
mkdir -p /nginx/live/
mkdir -p /nginx/logs/
mkdir -p /nginx/cache/
mkdir -p /hostdata/

#Modules.
mkdir -p /opt/nginx/modules/
cd /opt/nginx/modules/
git clone https://github.com/ildus/nginx_redis.git
cd nginx_redis/
mv ngx_devel_kit-0.2.19/ /opt/nginx/modules/

cd /opt/nginx/modules/
rm -Rf nginx_redis/
cd /opt/nginx/modules/
git clone https://github.com/openresty/set-misc-nginx-module.git
git clone https://github.com/vozlt/nginx-module-vts.git
git clone https://github.com/FRiCKLE/ngx_cache_purge.git
git clone https://github.com/kyprizel/testcookie-nginx-module.git
git clone https://github.com/openresty/headers-more-nginx-module.git
git clone https://github.com/openresty/echo-nginx-module.git
git clone https://github.com/arut/nginx-dav-ext-module.git
git clone https://github.com/masterzen/nginx-upload-progress-module.git
git clone https://github.com/nginx-clojure/nginx-access-plus.git
git clone https://github.com/leev/ngx_http_geoip2_module.git
git clone https://github.com/flant/nginx-http-rdns.git
git clone https://github.com/dizballanze/ngx_http_avatars_gen_module.git
git clone https://github.com/openresty/lua-nginx-module.git

#NEW
git clone https://github.com/arut/nginx-mtask-module.git
git clone https://github.com/arut/nginx-mysql-module.git
git clone  https://github.com/SpiderLabs/ModSecurity-nginx.git
git clone https://github.com/kvspb/nginx-auth-ldap.git
git clone https://github.com/Vasfed/nginx_ipset_blacklist.git
git clone https://github.com/openresty/encrypted-session-nginx-module.git
git clone https://github.com/Qihoo360/ngx_http_subrange_module.git
#END-NEW

wget https://github.com/pagespeed/ngx_pagespeed/archive/v1.12.34.2-beta.zip
unzip v1.12.34.2-beta.zip
rm -Rf v1.12.34.2-beta.zip

#Pagespeed Library
cd /opt/nginx/modules/ngx_pagespeed-1.12.34.2-beta
wget https://dl.google.com/dl/page-speed/psol/1.12.34.2-x64.tar.gz
tar -xzvf 1.12.34.2-x64.tar.gz
