./configure \
--with-compat \
--add-dynamic-module=/opt/nginx/modules/ngx_devel_kit \
--add-dynamic-module=/opt/nginx/modules/testcookie-nginx-module \
--add-dynamic-module=/opt/nginx/modules/headers-more-nginx-module \
--add-dynamic-module=/opt/nginx/modules/echo-nginx-module \
--add-dynamic-module=/opt/nginx/modules/nginx-dav-ext-module \
--add-dynamic-module=/opt/nginx/modules/nginx-access-plus/src/c \
--add-dynamic-module=/opt/nginx/modules/ngx_http_geoip2_module \
--add-dynamic-module=/opt/nginx/modules/ngx_pagespeed-1.12.34.2-beta \
--add-dynamic-module=/opt/nginx/modules/nginx-rtmp-module \
--add-dynamic-module=/opt/nginx/modules/ngx-fancyindex
